#!/usr/bin/env php
<?php

use Eloquent\Asplode\Asplode;
use Eloquent\Phony as x;

require __DIR__ . '/../../../vendor/autoload.php';

Asplode::install();
error_reporting(-1);

// should record passing mock assertions
$proxy = x\mock('Eloquent\Phony\Test\TestClassA');
$mock = $proxy->mock();
$mock->testClassAMethodA('a', 'b');

$proxy->testClassAMethodA->calledWith('a', 'b');

// should record failing mock assertions
$proxy = x\mock('Eloquent\Phony\Test\TestClassA');
$mock = $proxy->mock();

$proxy->testClassAMethodA->calledWith('a', 'b');
