#!/usr/bin/env php
<?php

use Eloquent\Phony as x;

require __DIR__ . '/../../../vendor/autoload.php';

// should record passing mock assertions
$handle = x\mock('Eloquent\Phony\Test\TestClassA');
$mock = $handle->get();
$mock->testClassAMethodA('aardvark', 'bonobo');

$handle->testClassAMethodA->calledWith('aardvark', 'bonobo');

// should record failing mock assertions
$handle = x\mock('Eloquent\Phony\Test\TestClassA');
$mock = $handle->get();
$mock->testClassAMethodA('aardvark', ['bonobo', 'capybara', 'dugong']);
$mock->testClassAMethodA('armadillo', ['bonobo', 'chameleon', 'dormouse']);

$handle->testClassAMethodA->calledWith('aardvark', ['bonobo', 'chameleon', 'dugong']);
