#!/usr/bin/env php
<?php

use Eloquent\Phony\Phony;

require __DIR__ . '/../../../vendor/autoload.php';

error_reporting(-1);

// should record passing mock assertions (static)
$proxy = Phony::mock('Eloquent\Phony\Test\TestClassA');
$mock = $proxy->mock();
$mock->testClassAMethodA('a', 'b');

$proxy->testClassAMethodA->calledWith('a', 'b');

// should record failing mock assertions (static)
$proxy = Phony::mock('Eloquent\Phony\Test\TestClassA');
$mock = $proxy->mock();

$proxy->testClassAMethodA->calledWith('a', 'b');
