#!/usr/bin/env bash

set -e

EXAMPLE="event-emitter"
echo "Event emitter examples ========================================================="
echo

echo "Peridot example ----------------------------------------------------------------"
"${BASH_SOURCE%/*}/$EXAMPLE/peridot/run"
echo

echo "Pho example --------------------------------------------------------------------"
"${BASH_SOURCE%/*}/$EXAMPLE/pho/run"
echo

echo "PHPUnit example ----------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/$EXAMPLE/phpunit/run"
echo

echo "SimpleTest example -------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/$EXAMPLE/simpletest/run"
echo
