#!/usr/bin/env php
<?php

/*
 * This file is part of the Phony package.
 *
 * Copyright © 2016 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

use Eloquent\Phony\Phony;

require __DIR__ . '/../../vendor/autoload.php';

Phony::mock('Icecave\Isolator\Isolator');
