#!/usr/bin/env php
<?php

/*
 * This file is part of the Phony package.
 *
 * Copyright © 2014 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

use Eloquent\Phony\Phony;

require __DIR__ . '/../../vendor/autoload.php';

$runs = 10;

$startTime = microtime(true);

for ($i = 0; $i < $runs; $i++) {
    $mock = Phony::mock('Icecave\Isolator\Isolator')->create();
}

$elapsedTime = microtime(true) - $startTime;
printf("Phony: %0.4f seconds\n", $elapsedTime);


$startTime = microtime(true);

for ($i = 0; $i < $runs; $i++) {
    $mock = Phake::partialMock('Icecave\Isolator\Isolator');
}

$elapsedTime = microtime(true) - $startTime;
printf("Phake: %0.4f seconds\n", $elapsedTime);
