<?php

/**
 * A mock class generated by Phony.
 *
 * @uses \stdClass
 *
 * This file is part of the Phony package.
 *
 * Copyright © 2014 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with the Phony source code.
 *
 * @link https://github.com/eloquent/phony
 */
class MockGeneratorSimple
extends \stdClass
implements \Eloquent\Phony\Mock\MockInterface
{
    private static $_staticStubs = array();
    private $_stubs = array();
}
