<?php

/**
 * A mock class generated by Phony.
 *
 * This file is part of the Phony package.
 *
 * Copyright © 2014 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with the Phony source code.
 *
 * @link https://github.com/eloquent/phony
 */
class MockGeneratorArrayConstant
implements \Eloquent\Phony\Mock\MockInterface
{
    const CONSTANT_A = array();
    const CONSTANT_B = array('a', 'b');
    const CONSTANT_C = array('a' => 'b', 'c' => 'd');

    private static $_staticStubs = array();
    private $_stubs = array();
}
