<?php

/**
 * A mock class generated by Phony.
 *
 * This file is part of the Phony package.
 *
 * Copyright © 2014 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with the Phony source code.
 *
 * @link https://github.com/eloquent/phony
 */
class MockGeneratorUndefinedTypeHint
implements \Eloquent\Phony\Mock\MockInterface
{
    /**
     * Custom method 'methodA'.
     *
     * @param \Non\Existent      $a0 Was 'first'.
     * @param \Non\Existent|null $a1 Was 'second'.
     */
    public function methodA(
        \Non\Existent $a0,
        \Non\Existent $a1 = null
    ) {
        $arguments = array($a0, $a1);
        for ($i = 2; $i < func_num_args(); $i++) {
            $arguments[] = func_get_arg($i);
        }

        $arguments = new \Eloquent\Phony\Call\Argument\Arguments($arguments);

        if (isset($this->_stubs[__FUNCTION__])) {
            return $this->_stubs[__FUNCTION__]->invokeWith($arguments);
        }
    }

    /**
     * Call a static parent method.
     *
     * @param string                                           $name      The method name.
     * @param \Eloquent\Phony\Call\Argument\ArgumentsInterface $arguments The arguments.
     */
    private static function _callParentStatic(
        $name,
        \Eloquent\Phony\Call\Argument\ArgumentsInterface $arguments
    ) {
        return call_user_func_array(
            array(__CLASS__, 'parent::' . $name),
            $arguments->all()
        );
    }

    /**
     * Call a parent method.
     *
     * @param string                                           $name      The method name.
     * @param \Eloquent\Phony\Call\Argument\ArgumentsInterface $arguments The arguments.
     */
    private function _callParent(
        $name,
        \Eloquent\Phony\Call\Argument\ArgumentsInterface $arguments
    ) {
        return call_user_func_array(
            array($this, 'parent::' . $name),
            $arguments->all()
        );
    }

    private static $_staticStubs = array();
    private $_stubs = array();
    private $_mockId;
}
