<?php

/**
 * A mock class generated by Phony.
 *
 * This file is part of the Phony package.
 *
 * Copyright © 2014 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with the Phony source code.
 *
 * @link https://github.com/eloquent/phony
 */
class MockGeneratorParameterConstantFallback
implements \Eloquent\Phony\Mock\MockInterface
{
    /**
     * Custom method 'methodA'.
     *
     * @param mixed $a0 Was 'first'.
     */
    public function methodA(
        $a0 = 256
    ) {
        if (isset($this->_stubs[__FUNCTION__])) {
            return call_user_func_array(
                $this->_stubs[__FUNCTION__],
                func_get_args()
            );
        }
    }

    private static $_staticStubs = array();
    private $_stubs = array();
}
