#!/bin/sh

echo
echo ===========================================================================
echo SimpleTest
echo ===========================================================================
echo

php test/integration/simpletest/index.php
