#!/bin/sh

echo
echo ===========================================================================
echo PHPUnit
echo ===========================================================================
echo

vendor/bin/phpunit test/integration/phpunit
