#!/usr/bin/env php
<?php

use Eloquent\Phony\Test\Facade\FacadeContainer;

require dirname(__DIR__) . '/vendor/autoload.php';

$inputPath = $argv[1];
$outputPath = $argv[2];

if (!($inputPath && $outputPath)) {
    error_log('Usage: build-hook-generator-fixture input-path output-path');
    exit(1);
}

$container = new FacadeContainer;
$invocableInspector = $container->invocableInspector;
$signatureInspector = $container->functionSignatureInspector;
$hookGenerator = $container->functionHookGenerator;

require $inputPath;

$signature = $signatureInspector
    ->signature($invocableInspector->callbackReflector($callback));
$source = $hookGenerator->generateHook($functionName, $namespace, $signature);

file_put_contents($outputPath, "<?php\n\n" . $source);
