#!/usr/bin/env php
<?php

use Eloquent\Asplode\Asplode;

require __DIR__ . '/../vendor/autoload.php';

Asplode::install();

echo 'Generating website... ';

passthru('mkdir -p build');

$hash = sha1_file('doc/index.md');
$content = null;

if (file_exists('build/web.json')) {
    $meta = json_decode(file_get_contents('build/web.json'));
    $needsRender = $meta->hash !== $hash;
    $content = $meta->content;
} else {
    $needsRender = true;
}

if ($needsRender) {
    $header = "Content-type: text/plain\r\n";

    if ($token = getenv('GITHUB_TOKEN')) {
        $header .= "Authorization: token $token\r\n";
    }

    $content = strtr(
        file_get_contents(
            'https://api.github.com/markdown/raw',
            false,
            stream_context_create(
                array(
                    'http' => array(
                        'user_agent' => 'PHP',
                        'header' => $header,
                        'method' => 'POST',
                        'content' => file_get_contents('doc/index.md'),
                    ),
                )
            )
        ),
        array(
            'id="user-content-' => 'id="',
            'name="user-content-' => 'name="',
        )
    );

    file_put_contents(
        'build/web.json',
        json_encode(
            array('content' => $content, 'hash' => $hash),
            JSON_PRETTY_PRINT
        )
    );
}

$header = file_get_contents('assets/web/header.tpl.html');
$footer = file_get_contents('assets/web/footer.tpl.html');
$content = rtrim($content, "\n");
$content = <<<EOD
$header
<!-- START content -->

$content

<!-- END content -->

$footer
EOD;

passthru('rm -rf web');
passthru('mkdir -p web');

file_put_contents('web/index.html', $content);

passthru('cp -a assets/web/css web/');
passthru('cp -a assets/web/data web/');
passthru('cp -a assets/web/img web/');
passthru('cp -a assets/web/js web/');
passthru('cp -a doc/img web/');

echo "done.\n";
