#!/usr/bin/env php
<?php

use Eloquent\Phony\Test\Facade\FacadeContainer;

require dirname(__DIR__) . '/vendor/autoload.php';

$inputPath = $argv[1];
$outputPath = $argv[2];

if (!($inputPath && $outputPath)) {
    error_log('Usage: build-mock-generator-fixture input-path output-path');
    exit(1);
}

$container = new FacadeContainer;
$factory = $container->mockBuilderFactory;

require $inputPath;

file_put_contents($outputPath, "<?php\n\n" . $builder->source());
