#!/usr/bin/env bash

set -e

if [[ -z "$1" ]]; then
  >&2 echo "Usage: gha-publish-doc clone-path"
  exit 1
fi

if [[ -z "$DOC_GITHUB_TOKEN" ]]; then
  >&2 echo "DOC_GITHUB_TOKEN must be set"
  exit 1
fi

cd "$1"
git push "https://${DOC_GITHUB_TOKEN}@github.com/eloquent/phony.git" gh-pages:gh-pages
