#!/usr/bin/env bash

set -e

if [[ -z "$TRAVIS_PHP_VERSION" ]]; then
    echo 'TRAVIS_PHP_VERSION not defined.'

    exit 1
fi

if [[ -z "$TRAVIS_BRANCH" ]]; then
    echo 'TRAVIS_BRANCH not defined.'

    exit 1
fi

if [[ -z "$TRAVIS_PULL_REQUEST" ]]; then
    echo 'TRAVIS_PULL_REQUEST not defined.'

    exit 1
fi

if [[ -z "$ELOQUENT_PUBLISH_VERSION" ]]; then
    echo 'ELOQUENT_PUBLISH_VERSION not defined.'

    exit 1
fi

if [[ "$TRAVIS_PHP_VERSION" == "$ELOQUENT_PUBLISH_VERSION" ]]; then
    make coverage
else
    make test
fi
