#!/usr/bin/env bash

set -e

if [[ -z "$TRAVIS_PHP_VERSION" ]]; then
    echo 'TRAVIS_PHP_VERSION not defined.'

    exit 1
fi

if [[ -z "$TRAVIS_BRANCH" ]]; then
    echo 'TRAVIS_BRANCH not defined.'

    exit 1
fi

if [[ -z "$TRAVIS_PULL_REQUEST" ]]; then
    echo 'TRAVIS_PULL_REQUEST not defined.'

    exit 1
fi

if [[ -z "$ELOQUENT_PUBLISH_VERSION" ]]; then
    echo 'ELOQUENT_PUBLISH_VERSION not defined.'

    exit 1
fi

echo "TRAVIS_PHP_VERSION is '$TRAVIS_PHP_VERSION'"
echo "TRAVIS_BRANCH is '$TRAVIS_BRANCH'"
echo "TRAVIS_TAG is '$TRAVIS_TAG'"
echo "TRAVIS_PULL_REQUEST is '$TRAVIS_PULL_REQUEST'"

if [[ "$TRAVIS_PHP_VERSION" == "$ELOQUENT_PUBLISH_VERSION" ]]; then
    bash <(curl -s https://codecov.io/bash)
fi
